"""Micro Rooster phase-1 robot: the Microduck walk model reshaped as a rooster.

robot_rooster.xml is generated by robot/microduck/make_rooster.py (12 servos,
STS3215 masses, longer legs, comb/wattle/tail). Servos use BAM's measured
Feetech STS3215 model (7.4 V, m1) in place of the XL330 M6 model.
"""

import os
from pathlib import Path

import mujoco
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg

from mjlab_microduck.actuator import RateLimitedTargetBamActuatorCfg
from mjlab_microduck.robot.microduck_constants import FULL_COLLISION, HOME_FRAME

MICROROOSTER_XML: Path = Path(os.path.dirname(__file__)) / "microduck" / "robot_rooster.xml"
assert MICROROOSTER_XML.exists(), f"Run make_rooster.py first: {MICROROOSTER_XML}"

# Trunk height with feet flat at the STAND pose (printed by make_rooster.py).
ROOSTER_STAND_Z = 0.1294


def get_rooster_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(MICROROOSTER_XML))


# Duck HOME pose minus the welded head_yaw / head_roll joints.
ROOSTER_HOME_FRAME = EntityCfg.InitialStateCfg(
    joint_pos={k: v for k, v in HOME_FRAME.joint_pos.items()
               if "head_yaw" not in k and "head_roll" not in k},
    joint_vel={".*": 0.0},
)

# Same DR as the duck (battery voltage, sag, command delay, friction scale),
# but the STS3215 model and its firmware default P gain (BAM STS3215Actuator:
# kp=32). The STS3215 params are an m1 fit (Coulomb + viscous only), so there
# is no load-dependent friction to match — measure the production servo and
# refit before trusting sim2real.
rooster_actuators = RateLimitedTargetBamActuatorCfg(
    motor_name="feetech_sts3215_7_4V",
    model="m1",
    target_names_expr=(r"^(?!passive_).*",),
    kp_fw=32.0,
    vin_range=(6.5, 8.2),
    vin_drop_gain_range=(0.0, 0.2),
    vin_min=6.0,
    delay_min_lag=3,
    delay_max_lag=6,
)

MICROROOSTER_ROBOT_CFG = EntityCfg(
    spec_fn=get_rooster_spec,
    init_state=ROOSTER_HOME_FRAME,
    collisions=(FULL_COLLISION,),
    articulation=EntityArticulationInfoCfg(
        actuators=(rooster_actuators,),
        soft_joint_pos_limit_factor=0.9,
    ),
)
